### ISSUE TITLE
Add ability to create polls and save in Personal Account

### ISSUE THREAD

**Issue by habur331** [InnoSWP/Hooty#17]
As a teacher I want to create quizzes to use during my speeches

**Comment by Mierley** [comment]
After discussion with customer we decided to implement for mvp v1 support of polls first. It will take smaller time for realization than for quizzes, however product will stay valuable

**Comment by Mierley** [comment]
- [ ] Ability to create Polls

- [ ] Ability to save in personal account

**Comment by Mierley** [comment]
Scenario:
